{
  products: getProducts {
    travel {
      image {
        path
      }
      title
      description
      productUrl
      productEmbedHtml
      addToHomepage
    }
    style {
      image {
        path
      }
      title
      description
      productUrl
      productEmbedHtml
      addToHomepage
    }
    photography {
      image {
        path
      }
      title
      description
      productUrl
      productEmbedHtml
      addToHomepage
    }
    beauty {
      image {
        path
      }
      title
      description
      productUrl
      productEmbedHtml
      addToHomepage
    }
    fitness {
      image {
        path
      }
      title
      description
      productUrl
      productEmbedHtml
      addToHomepage
    }
    home {
      image {
        path
      }
      title
      description
      productUrl
      productEmbedHtml
      addToHomepage
    }
    wedding {
      image {
        path
      }
      title
      description
      productUrl
      productEmbedHtml
      addToHomepage
    }
  }
  blogShopFallback: getBlog {
    travelEssentialsItems {
      image {
        path
        filename
        title
        description
      }
      title
      productUrl
      productEmbedHtml
    }
  }
  categories: getBlog {
    categories {
      title
      parentCategory {
        title
      }
    }
  }
  importantAutoStories: getStoryList(
    size: 100
    where: {isImportant: {eq: true}}
    sort: [{field: "_enabledAt", order: "desc"}]
  ) {
    total
    items {
      _contentTypeName
      _status
      _enabledAt
      _updatedAt
      isImportant
      title
      slug
      social {
        title
      }
      category {
        title
        parentCategory {
          title
        }
      }
      tout {
        image {
          path
        }
      }
    }
  }
  fallbackAutoStories: getStoryList(
    size: 100
    sort: [{field: "_enabledAt", order: "desc"}]
  ) {
    items {
      _status
      _enabledAt
      _updatedAt
      title
      slug
      social {
        title
      }
      category {
        title
        parentCategory {
          title
        }
      }
      tout {
        image {
          path
        }
      }
    }
  }
  relatedMainCategories: getMainCategoryList(size: 250, onlyEnabled: false) {
    items {
      _id
      title
      storySet(
        size: 12
        onlyEnabled: true
        sort: [{field: "_enabledAt", order: "desc"}]
      ) {
        items {
          _contentTypeName
          _status
          _enabledAt
          _updatedAt
          isImportant
          title
          slug
          category {
            title
          }
          social {
            title
          }
          tout {
            image {
              path
            }
          }
        }
      }
    }
  }
  relatedCategories: getCategoryList(size: 250, onlyEnabled: false) {
    items {
      _id
      title
      storySet(
        size: 12
        onlyEnabled: true
        sort: [{field: "_enabledAt", order: "desc"}]
      ) {
        items {
          _contentTypeName
          _status
          _enabledAt
          _updatedAt
          isImportant
          title
          slug
          category {
            title
          }
          social {
            title
          }
          tout {
            image {
              path
            }
          }
        }
      }
    }
  }
  relatedLocations: getLocationList(size: 250, onlyEnabled: false) {
    items {
      _id
      title
      storySet(
        size: 12
        onlyEnabled: true
        sort: [{field: "_enabledAt", order: "desc"}]
      ) {
        items {
          _contentTypeName
          _status
          _enabledAt
          _updatedAt
          isImportant
          title
          slug
          category {
            title
          }
          social {
            title
          }
          tout {
            image {
              path
            }
          }
        }
      }
    }
  }
  relatedContinents: getContinentList(size: 250, onlyEnabled: false) {
    items {
      _id
      name
      storySet(
        size: 12
        onlyEnabled: true
        sort: [{field: "_enabledAt", order: "desc"}]
      ) {
        items {
          _contentTypeName
          _status
          _enabledAt
          _updatedAt
          isImportant
          title
          slug
          category {
            title
          }
          social {
            title
          }
          tout {
            image {
              path
            }
          }
        }
      }
    }
  }
}
