query ContinentDestinationDetailPages {
  getContinentList(size: 50, onlyEnabled: true) {
    items {
      _id
      _contentTypeName
      name
      social {
        title
        description
        image {
          path
        }
      }
      locations {
        _id
        _contentTypeName
        title
        storySet(
          size: 250
          onlyEnabled: true
          sort: [{field: "_enabledAt", order: "desc"}]
        ) {
          total
          items {
            _id
            _contentTypeName
            title
            slug
            category {
              title
            }
            mainCategory {
              title
            }
            tout {
              image {
                path
              }
              dek
            }
          }
        }
      }
      storySet(
        size: 250
        onlyEnabled: true
        sort: [{field: "_enabledAt", order: "desc"}]
      ) {
        total
        items {
          _id
          _contentTypeName
          title
          slug
          category {
            title
          }
          mainCategory {
            title
          }
          tout {
            image {
              path
            }
            dek
          }
        }
      }
    }
    total
  }
}
