query {
  page: getFilms {
    _contentTypeName
    title
    filmCategories {
      title
    }
    featuredFilms {
      _id
      title
      image {
        path
      }
      youTubeUrl
    }
    social {
      title
      description
      image {
        path
      }
    }
  }
  allFilms: getFilmList(size: 100, sort: [{field: "_enabledAt", order: "desc"}]) {
    items {
      _id
      _enabledAt
      title
      image { path }
      youTubeUrl
      filmCategory { title }
    }
    total
  }
}
