query {
  page: getHomepage {
    _contentTypeName
    slider {
      interval
      slides {
        image {
          path
        }
        caption {
          text
          url
        }
      }
    }
    social {
      title
      description
      image {
        path
      }
    }
  }

  blog: getBlog {
    featuredStory {
      _contentTypeName
      _enabledAt
      title
      slug
      category {
        title
      }
      tout {
        image {
          path
        }
        dek
      }
    }
  }

  featuredCategories: getCategoryList {
    items {
      title
      storySet(size: 6, sort: [{field: "_enabledAt", order: "desc"}]) {
        items {
          _contentTypeName
          _enabledAt
          title
          slug
          category {
            title
          }
          tout {
            image {
              path
            }
            dek
          }
        }
      }
    }
  }

  stories: getStoryList {
    items {
      _enabledAt
      title
      slug
      tout {
        image {
          path
        }
        dek
      }
      category {
        title
      }
    }
  }
}
