query DestinationDetailContext {
  franceOutfit: getStory(_id: "06621abf-16d7-4f2a-b6db-4c8df53ce6fa") {
    _id
    _contentTypeName
    _enabledAt
    isImportant
    title
    slug
    category { title }
    mainCategory { title }
    tout { image { path } dek }
  }
  franceBeaches: getStory(_id: "07ace99c-1e4d-4a7d-b4da-46c6b99b2a32") {
    _id
    _contentTypeName
    _enabledAt
    isImportant
    title
    slug
    category { title }
    mainCategory { title }
    tout { image { path } dek }
  }
  franceFeature: getStory(_id: "0c212cc6-243e-4daa-8202-eb76c0b0a04e") {
    _id
    _contentTypeName
    _enabledAt
    isImportant
    title
    slug
    category { title }
    mainCategory { title }
    tout { image { path } dek }
  }
}
