query DestinationDetailPages {
  getLocationList(size: 250, onlyEnabled: true) {
    items {
      _id
      _contentTypeName
      title
      social {
        title
        description
        image {
          path
        }
      }
      continentSet(size: 1, onlyEnabled: true) {
        items {
          locations {
            _id
            _contentTypeName
            title
          }
        }
      }
      storySet(
        size: 250
        onlyEnabled: true
        sort: [{field: "_enabledAt", order: "desc"}]
      ) {
        total
        items {
          _id
          _contentTypeName
          title
          slug
          category {
            title
          }
          mainCategory {
            title
          }
          tout {
            image {
              path
            }
            dek
          }
        }
      }
    }
    total
  }
}
