query($images: TSImagesConfig) {
  categories: getCategoryList(size: 250, from: 0, sort: [{field: "navigationOrder", order: "asc"}]) {
    items {
      title
      parentCategory { title }
    }
  }
  stories1: getStoryList(size: 250, from: 0, sort: [{field: "_enabledAt", order: "desc"}]) {
    items { ...SearchStoryFields }
  }
  stories2: getStoryList(size: 250, from: 250, sort: [{field: "_enabledAt", order: "desc"}]) {
    items { ...SearchStoryFields }
  }
  stories3: getStoryList(size: 250, from: 500, sort: [{field: "_enabledAt", order: "desc"}]) {
    items { ...SearchStoryFields }
  }
  stories4: getStoryList(size: 250, from: 750, sort: [{field: "_enabledAt", order: "desc"}]) {
    items { ...SearchStoryFields }
  }
}

fragment SearchStoryFields on Story {
      _contentTypeName
      _enabledAt
      isImportant
      title
      slug
      category {
        title
      }
      location {
        title
      }
      contentHtml(images: $images)
      extraContentBlocks {
        contentHtml(images: $images)
      }
      extraHtmlBlocks {
        html
      }
      extraTableBlocks {
        pastedText
        columnCount
      }
      mainHtmlBlock1
      mainContentBlock1Html(images: $images)
      additionalMainBlocks {
        mainHtmlBlock2
        mainContentBlock2Html(images: $images)
        mainHtmlBlock3
        mainContentBlock3Html(images: $images)
        mainHtmlBlock4
        mainContentBlock4Html(images: $images)
        mainHtmlBlock5
        mainContentBlock5Html(images: $images)
        mainHtmlBlock6
        mainContentBlock6Html(images: $images)
      }
      mainHtmlBlock2
      mainContentBlock2Html(images: $images)
      mainHtmlBlock3
      mainContentBlock3Html(images: $images)
      mainHtmlBlock4
      mainContentBlock4Html(images: $images)
      mainHtmlBlock5
      mainContentBlock5Html(images: $images)
      mainHtmlBlock6
      mainContentBlock6Html(images: $images)
      contentBlocks {
        __typename
        ... on ContentBlock {
          contentHtml(images: $images)
        }
        ... on HtmlBlock {
          html
        }
        ... on TableBlock {
          pastedText
          columnCount
        }
        ... on StoryImageBlock {
          image { path }
          size
          alignment
          cropPosition
          spacing
          linkUrl
          linkTarget
          caption
          altText
          label
        }
        ... on StoryGalleryBlock {
          layout
          size
          label
          images {
            image { path }
            linkUrl
            caption
            altText
          }
        }
      }
      tout {
        image {
          path
        }
        dek
      }
      social {
        title
        description
      }
}
