query($images: TSImagesConfig) {
  getStoryList(where: {slug: {regexp: ".+"}}) {
    items {
      _contentTypeName
      _status
      _enabledAt
      _updatedAt
      title
      slug
      isImportant
      postType
      pageLayout
      atAGlance {
        kicker
        title
        summary
        item1Section
        item1Title
        item1Link
        item2Section
        item2Title
        item2Link
        item3Section
        item3Title
        item3Link
      }
      shopEditTitle
      shopEditEnabled
      shopEditItems {
        image {
          path
        }
        title
        productUrl
        productEmbedHtml
      }
      firstHandExpertise {
        kicker
        title
        text
      }
      keepReadingKicker
      keepReadingTitle
      categoryLabels: category { title }
      category {
        title
        storySet(size: 12, sort: [{field: "_enabledAt", order: "desc"}]) {
          items {
            _contentTypeName
            _enabledAt
            isImportant
            title
            slug
            category { title }
            social {
              title
            }
            tout {
              image {
                path
              }
            }
          }
        }
      }
      location {
        title
        storySet(size: 12, sort: [{field: "_enabledAt", order: "desc"}]) {
          items {
            _contentTypeName
            _enabledAt
            isImportant
            title
            slug
            category { title }
            social {
              title
            }
            tout {
              image {
                path
              }
            }
          }
        }
      }
      contentHtml(images: $images)
      extraContentBlocks {
        contentHtml(images: $images)
      }
      extraHtmlBlocks {
        html
      }
      extraTableBlocks {
        pastedText
        columnCount
      }
      mainHtmlBlock1
      mainContentBlock1Html(images: $images)
      additionalMainBlocks {
        mainHtmlBlock2
        mainContentBlock2Html(images: $images)
        mainHtmlBlock3
        mainContentBlock3Html(images: $images)
        mainHtmlBlock4
        mainContentBlock4Html(images: $images)
        mainHtmlBlock5
        mainContentBlock5Html(images: $images)
        mainHtmlBlock6
        mainContentBlock6Html(images: $images)
      }
      mainHtmlBlock2
      mainContentBlock2Html(images: $images)
      mainHtmlBlock3
      mainContentBlock3Html(images: $images)
      mainHtmlBlock4
      mainContentBlock4Html(images: $images)
      mainHtmlBlock5
      mainContentBlock5Html(images: $images)
      mainHtmlBlock6
      mainContentBlock6Html(images: $images)
      contentBlocks {
        __typename
        ... on ContentBlock {
          contentHtml(images: $images)
        }
        ... on HtmlBlock {
          html
        }
        ... on TableBlock {
          pastedText
          columnCount
        }
        ... on StoryImageBlock {
          image { path }
          size
          alignment
          cropPosition
          spacing
          linkUrl
          linkTarget
          caption
          altText
          label
        }
        ... on StoryGalleryBlock {
          layout
          size
          label
          images {
            image { path }
            linkUrl
            caption
            altText
          }
        }
      }
      relatedStories {
        _enabledAt
        isImportant
        title
        slug
        category {
          title
        }
        social {
          title
        }
        tout {
          image {
            path
          }
        }
      }
      tout {
        image {
          path
        }
        caption
        secondaryImage {
          path
        }
        dek
      }
      social {
        title
        description
        image {
          path
        }
      }
    }
    total
  }
}
