query {
  products: getProducts {
    travel { image { path } title description productUrl productEmbedHtml addToHomepage }
    style { image { path } title description productUrl productEmbedHtml addToHomepage }
    photography { image { path } title description productUrl productEmbedHtml addToHomepage }
    beauty { image { path } title description productUrl productEmbedHtml addToHomepage }
    fitness { image { path } title description productUrl productEmbedHtml addToHomepage }
    home { image { path } title description productUrl productEmbedHtml addToHomepage }
    wedding { image { path } title description productUrl productEmbedHtml addToHomepage }
  }
  blogShopFallback: getBlog {
    travelEssentialsItems {
          image {
            path
            filename
            title
            description
          }
      title
      productUrl
      productEmbedHtml
    }
  }
  categories: getBlog {
    categories {
      title
      parentCategory { title }
    }
  }
  featuredCategories: getCategoryList {
    items {
      title
      storySet(size: 6, onlyEnabled: true) {
        items {
          _contentTypeName
          _status
          _enabledAt
          _updatedAt
          isImportant
          title
          slug
          social {
            title
          }
          category { title parentCategory { title } }
          location {
            title
          }
          tout {
            image {
              path
            }
            dek
          }
        }
      }
    }
  }
  featuredCategoryCandidates: getCategoryList {
    items {
      title
      storySet(size: 12, onlyEnabled: true, sort: [{field: "_enabledAt", order: "desc"}]) {
        items {
          _contentTypeName
          _status
          _enabledAt
          _updatedAt
          isImportant
          title
          slug
          category { title parentCategory { title } }
          tout {
            image {
              path
              filename
              title
              description
            }
            dek
          }
        }
      }
    }
  }
  importantAutoStories: getStoryList(
    size: 100,
    where: {isImportant: {eq: true}},
    sort: [{field: "_enabledAt", order: "desc"}]
  ) {
    total
    items {
      _contentTypeName
      _status
      _enabledAt
      _updatedAt
      isImportant
      title
      slug
      social { title }
      category { title parentCategory { title } }
      tout { image { path } }
    }
  }
  fallbackAutoStories: getStoryList(size: 100, sort: [{field: "_enabledAt", order: "desc"}]) {
    items {
      _status
      _enabledAt
      _updatedAt
      title
      slug
      social { title }
      category { title parentCategory { title } }
      tout { image { path } }
    }
  }
  archiveStories1: getStoryList(size: 250, from: 0, onlyEnabled: true, sort: [{field: "_enabledAt", order: "desc"}]) {
    items {
      _contentTypeName
      _status
      _enabledAt
      isImportant
      title
      slug
      social { title description }
      category { title parentCategory { title } }
      tout { image { path } dek }
    }
  }
  archiveStories2: getStoryList(size: 250, from: 250, onlyEnabled: true, sort: [{field: "_enabledAt", order: "desc"}]) {
    items {
      _contentTypeName
      _status
      _enabledAt
      isImportant
      title
      slug
      social { title description }
      category { title parentCategory { title } }
      tout { image { path } dek }
    }
  }
  archiveStories3: getStoryList(size: 250, from: 500, onlyEnabled: true, sort: [{field: "_enabledAt", order: "desc"}]) {
    items {
      _contentTypeName
      _status
      _enabledAt
      isImportant
      title
      slug
      social { title description }
      category { title parentCategory { title } }
      tout { image { path } dek }
    }
  }
  archiveStories4: getStoryList(size: 250, from: 750, onlyEnabled: true, sort: [{field: "_enabledAt", order: "desc"}]) {
    items {
      _contentTypeName
      _status
      _enabledAt
      isImportant
      title
      slug
      social { title description }
      category { title parentCategory { title } }
      tout { image { path } dek }
    }
  }
  shoppingStories: getStoryList(
    size: 8,
    where: {shopEditItems: {productUrl: {regexp: ".+"}}},
    sort: [{field: "_enabledAt", order: "desc"}]
  ) {
    items {
      _contentTypeName
      title
      slug
      shopEditItems {
        image { path }
        title
        productUrl
        productEmbedHtml
      }
    }
  }
  page: getBlog {
    _contentTypeName
    title
    featuredStory {
      _contentTypeName
      _enabledAt
      title
      slug
      category { title parentCategory { title } }
      tout {
        image {
          path
        }
        dek
      }
      shopEditItems {
        image { path }
        title
        productUrl
        productEmbedHtml
      }
    }
    heroImageOverride { path }
    heroImageFocus
    supportingStories {
      _contentTypeName title slug category { title parentCategory { title } }
      tout { image { path } dek }
    }
    editorsPicks {
      _contentTypeName title slug category { title parentCategory { title } }
      tout { image { path } dek }
    }
    travelEssentialsBackgroundImage { path }
    travelEssentialsBackgroundFocus
    travelEssentialsLabel
    travelEssentialsTitle
    travelEssentialsLinkText
    travelEssentialsLinkUrl
    travelEssentialsItems { image { path } title description productUrl productEmbedHtml }
    categoryTile1Category { title parentCategory { title } }
    categoryTile1Image { path }
    categoryTile1Focus
    categoryTile2Category { title parentCategory { title } }
    categoryTile2Image { path }
    categoryTile2Focus
    categoryTile3Category { title parentCategory { title } }
    categoryTile3Image { path }
    categoryTile3Focus
    categoryTile4Category { title parentCategory { title } }
    categoryTile4Image { path }
    categoryTile4Focus
    categoryTile5Category { title parentCategory { title } }
    categoryTile5Image { path }
    categoryTile5Focus
    categoryTile6Category { title parentCategory { title } }
    categoryTile6Image { path }
    categoryTile6Focus
    categoryTile7Category { title parentCategory { title } }
    categoryTile7Image { path }
    categoryTile7Focus
    categoryTile8Category { title parentCategory { title } }
    categoryTile8Image { path }
    categoryTile8Focus
    revolveSectionTitle
    revolveSectionLinkUrl
    revolveSectionEmbedHtml
    featuredItineraries {
      _contentTypeName title slug category { title parentCategory { title } }
      tout { image { path } dek }
    }
    leftFullBleedStory {
      _contentTypeName title slug category { title parentCategory { title } }
      tout { image { path } dek }
    }
    leftFullBleedImageOverride { path }
    leftFullBleedImageFocus
    leftFullBleedMobileImageOverride { path }
    leftFullBleedMobileImageFocus
    rightFullBleedStory {
      _contentTypeName title slug category { title parentCategory { title } }
      tout { image { path } dek }
    }
    rightFullBleedImageOverride { path }
    rightFullBleedImageFocus
    rightFullBleedMobileImageOverride { path }
    rightFullBleedMobileImageFocus
    latestStories {
      _contentTypeName title slug category { title parentCategory { title } }
      tout { image { path } dek }
    }
    categories {
      title
    }
    social {
      title
      description
      image {
        path
      }
    }
  }

}
