query($images: TSImagesConfig) {
  getStoryList {
    items {
      _contentTypeName
      _enabledAt
      _updatedAt
      title
      slug
      postType
      pageLayout
      shopEditTitle
      shopEditItems {
        image {
          path
        }
        title
        productUrl
      }
      firstHandExpertise {
        kicker
        title
        text
      }
      keepReadingKicker
      keepReadingTitle
      category {
        title
        storySet(size: 6, sort: [{field: "_enabledAt", order: "desc"}]) {
          items {
            _contentTypeName
            title
            slug
            social {
              title
            }
            tout {
              image {
                path
              }
            }
          }
        }
      }
      location {
        title
        storySet(size: 6, sort: [{field: "_enabledAt", order: "desc"}]) {
          items {
            _contentTypeName
            title
            slug
            social {
              title
            }
            tout {
              image {
                path
              }
            }
          }
        }
      }
      contentHtml(images: $images)
      mainHtmlBlock1
      mainContentBlock1Html(images: $images)
      additionalMainBlocks {
        mainHtmlBlock2
        mainContentBlock2Html(images: $images)
        mainHtmlBlock3
        mainContentBlock3Html(images: $images)
        mainHtmlBlock4
        mainContentBlock4Html(images: $images)
        mainHtmlBlock5
        mainContentBlock5Html(images: $images)
        mainHtmlBlock6
        mainContentBlock6Html(images: $images)
      }
      mainHtmlBlock2
      mainContentBlock2Html(images: $images)
      mainHtmlBlock3
      mainContentBlock3Html(images: $images)
      mainHtmlBlock4
      mainContentBlock4Html(images: $images)
      mainHtmlBlock5
      mainContentBlock5Html(images: $images)
      mainHtmlBlock6
      mainContentBlock6Html(images: $images)
      contentBlocks {
        __typename
        ... on ContentBlock {
          contentHtml(images: $images)
        }
        ... on HtmlBlock {
          html
        }
        ... on TableBlock {
          title
          dek
          pastedText
          columnCount
          headersText
          rowsText
          footnote
        }
        ... on StoryImageBlock {
          label
          image {
            path
          }
          size
          alignment
          caption
          altText
          linkUrl
          linkTarget
        }
        ... on StoryGalleryBlock {
          label
          layout
          size
          images {
            image {
              path
            }
            caption
            altText
            linkUrl
          }
        }
      }
      relatedStories {
        title
        slug
        social {
          title
        }
        tout {
          image {
            path
          }
        }
      }
      tout {
        image {
          path
        }
        secondaryImage {
          path
        }
        dek
      }
      social {
        title
        description
        image {
          path
        }
      }
    }
    total
  }
}
